### ISSUE TITLE
Unable to send messages Mac OS

### ISSUE THREAD

**Issue by sidneyarcidiacono** [oxen-io/session-desktop#1704]
**Describe the bug**

No outgoing messages send, always resolve with "SEND FAILED" error. 
Attempt to create closed group resolves with "Unable to send invites to all users"
Unable to update profile image.

**To Reproduce**

1. Log into Session desktop for Mac OS (latest from https://getsession.org)
2. Click "+" to add new message & enter recipient's Session ID *or* click contact's username on left-hand nav
3. Create message, click send or hit enter

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
Mac Pro 2019
* OS: [e.g. Ubuntu 16.04, Windows 10]
Big Sur 11.4 (I know, I know)
* Session Version or Git commit hash:
Session desktop mac 1.6.5

**Comment by KeeJef** [comment]
If you right click on the message when it fails to send and look at more information does it give any additional relevant info?

**Comment by sidneyarcidiacono** [comment]
Ah, yes, it does: "Ran out of swarm nodes to query" when right-clicking on the failed message and selecting "More Information". 

When testing this, I was able to get a message to send on desktop -- it's possible this was just an issue for a few days, but please let me know if there's anything else I can do or information I can provide that would be helpful to you.

**Comment by KeeJef** [comment]
Hmmm, thanks for the info @sidneyarcidiacono , sounds like it might be an issue related to management of the clients local Service Node list, @Bilb

**Comment by Bilb** [comment]
I fixed a bug which might be the cause of this. This is not released yet.
@sidneyarcidiacono  If you endup in the similar situation, could you share your logs so I can debug more? 
Try to resend a failing message, wait for it to fail again and then send me the logs .  
Thanks

**Comment by Bilb** [comment]
@sidneyarcidiacono a new release is up. let me know how it goes

**Comment by paihk** [comment]
Mac OS 11.4, Session 1.6.9

Still can't send new messages. 

THX!
