### ISSUE TITLE
Disappearing messages leave attachments on disk

### ISSUE THREAD

**Issue by smss2022** [oxen-io/session-desktop#2594]
**Describe the bug**
When messages are set to auto-delete after a period of time, their attachments remain on disk (in attachments_noindex/$random_hex_subdir)

**To Reproduce**
1. set the disappearing messages timer;
2. send/receive messages with attachments (e.g. pictures/gifs)

**Other information (please complete the following information):**

* PC
* Microsoft Windows [Version 10.0.22000.1165]
* Session Version 1.10.3

Might be related to https://github.com/oxen-io/session-desktop/issues/2567

**Comment by KeeJef** [comment]
Closing for #2567 we will have a look into this, we are currently refactoring disappearing message code so should be fixed in that release

**Comment by smss2022** [comment]
FYI: The issue is still present in the latest version (1.12.0).

**Comment by KeeJef** [comment]
> FYI: The issue is still present in the latest version (1.12.0).

Which mode are you using, can you explain the case in which attachments are not being removed?

**Comment by smss2022** [comment]
> Which mode are you using?
"Disappear after read", 1h

-I send or receive message with an image (jpg) in attachment;
-one hour after the message has been read it auto-distructs and disappears from the respective chat;
-the jpg is still present in [...]Session\attachments.noindex\[random_hex_name] (encrypted, but taking space);
-manual deletion is the only way of freeing space, otherwise the attachments will accumulate on disk.
