### ISSUE TITLE
Contacts reappear after being deleted

### ISSUE THREAD

**Issue by BeHooman** [oxen-io/session-desktop#2604]
**Describe the bug**
Contacts reappear after being deleted

**To Reproduce**
- open session
- delete a contact/conversation
- wait a few hours/days

**Other information (please complete the following information):**

* Device: MacBook Pro M1 2020
* OS: macOS 13.1
* Session Version or Git commit hash: session v 1.10.4

**Comment by KeeJef** [comment]
Yeah we are aware of this one, hopefully will be fixed when we update the way that we manage configuration messages in the new year, currently deletion of contacts is not synced across linked devices, and having linked devices can restore old configuration content like contacts.

**Comment by sysfu** [comment]
Any progress on this issue? Been six months and no fix in the latest releases. If there's a bug bounty for this that we can chip in to raise $$ for a fix, please post.

**Comment by KeeJef** [comment]
> Any progress on this issue? Been six months and no fix in the latest releases. If there's a bug bounty for this that we can chip in to raise $$ for a fix, please post.

User config release coming soon, should resolve this

**Comment by sysfu** [comment]
Just upgraded to the new ios and linux-desktop released today, but it seems that this issue persists, has anyone else seen resolution with the latest software updates?

**Comment by sysfu** [comment]
Recent blog post clarifies:

"Important: While all these changes are packaged up in this update, they won’t be enabled in-app until July 31"

https://getsession.org/blog/session-release-roundup-17

**Comment by KeeJef** [comment]
This should be fixed now that user config has been enabled
