### ISSUE TITLE
[BUG] Most attempts to send an image fail with error ENETUNREACH

### ISSUE THREAD

**Issue by Darker** [oxen-io/session-desktop#2972]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

90% of time, if I try to send an image/file to any chat, I get an error. In the log I see this:

```
INFO  2023-11-02T13:45:06.261Z Adding attachment padding...
WARN  2023-11-02T13:45:06.261Z tried to upload file to FileServer without image.. skipping
WARN  2023-11-02T13:45:10.815Z sendOnionRequestNoRetries error message:  ENETUNREACH
WARN  2023-11-02T13:45:10.815Z sendViaOnionV4ToNonSnodeRetryable failed  ENETUNREACH false
WARN  2023-11-02T13:45:10.816Z upload to file server v2 failed
ERROR 2023-11-02T13:45:10.816Z Message.saveErrors: null Error: upload to file server v2 of image.png failed
    at uploadToFileServer ([REDACTED]\ts\session\utils\Attachments.js:74:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async MessageModel.uploadData ([REDACTED]\ts\models\message.js:525:47)
    at async MessageModel.retrySend ([REDACTED]\ts\models\message.js:584:74)
    at async [REDACTED]\ts\components\conversation\message\message-content\MessageContextMenu.js:119:13
```

### Expected Behavior

Sending images to friends is a feature that should work at least most of the time.

### Steps To Reproduce

Windows 10. No special firewall. Works on the same network from android.

### Desktop Version

v1.11.4

### Anything else?

Longer log. The message about updating fileserver appears often and is suspicious but I don't know what it means:

```
INFO  2023-11-02T13:30:01.820Z Fileserver has no update so we are not looking for an update from github current:1.11.4 fromFileServer:v1.11.4
INFO  2023-11-02T13:30:51.543Z [updater] about to fetchReleaseFromFSAndUpdateMain
WARN  2023-11-02T13:30:51.998Z sendOnionRequestNoRetries error message:  ENETUNREACH
WARN  2023-11-02T13:30:51.998Z sendViaOnionV4ToNonSnodeRetryable failed  ENETUNREACH false
INFO  2023-11-02T13:30:51.998Z [updater] fetched latest release from fileserver:  null
INFO  2023-11-02T13:31:51.555Z [updater] about to fetchReleaseFromFSAndUpdateMain
WARN  2023-11-02T13:31:52.879Z sendOnionRequestNoRetries error message:  ENETUNREACH
WARN  2023-11-02T13:31:52.880Z sendViaOnionV4ToNonSnodeRetryable failed  ENETUNREACH false
INFO  2023-11-02T13:31:52.880Z [updater] fetched latest release from fileserver:  null
INFO  2023-11-02T13:32:51.551Z [updater] about to fetchReleaseFromFSAndUpdateMain
WARN  2023-11-02T13:32:52.007Z sendOnionRequestNoRetries error message:  ENETUNREACH
WARN  2023-11-02T13:32:52.007Z sendViaOnionV4ToNonSnodeRetryable failed  ENETUNREACH false
INFO  2023-11-02T13:32:52.007Z [updater] fetched latest release from fileserver:  null
INFO  2023-11-02T13:33:51.549Z [updater] about to fetchReleaseFromFSAndUpdateMain
INFO  2023-11-02T13:33:53.636Z [updater] fetched latest release from fileserver:  v1.11.4
INFO  2023-11-02T13:34:51.555Z [updater] about to fetchReleaseFromFSAndUpdateMain
WARN  2023-11-02T13:34:52.074Z sendOnionRequestNoRetries error message:  ENETUNREACH
WARN  2023-11-02T13:34:52.074Z sendViaOnionV4ToNonSnodeRetryable failed  ENETUNREACH false
INFO  2023-11-02T13:34:52.074Z [updater] fetched latest release from fileserver:  null
INFO  2023-11-02T13:34:53.796Z Adding attachment from clipboard {}
INFO  2023-11-02T13:35:00.597Z [updater] about to fetchReleaseFromFSAndUpdateMain
INFO  2023-11-02T13:35:02.658Z [updater] fetched latest release from fileserver:  v1.11.4
INFO  2023-11-02T13:35:05.828Z Sending message to conversation group([REDACTED]66a)) with networkTimestamp:  1698932104583
INFO  2023-11-02T13:35:06.808Z job runner adding type :"ConfigurationSyncJobType" 
INFO  2023-11-02T13:35:07.150Z Adding attachment padding...
WARN  2023-11-02T13:35:07.150Z tried to upload file to FileServer without image.. skipping
INFO  2023-11-02T13:35:07.190Z Loading 30 messages took 159ms to load.
INFO  2023-11-02T13:35:07.949Z those variants needs push: "ConvoInfoVolatileConfig"
WARN  2023-11-02T13:35:11.262Z sendOnionRequestNoRetries error message:  ENETUNREACH
WARN  2023-11-02T13:35:11.262Z sendViaOnionV4ToNonSnodeRetryable failed  ENETUNREACH false
WARN  2023-11-02T13:35:11.262Z upload to file server v2 failed
ERROR 2023-11-02T13:35:11.262Z Message.saveErrors: null Error: upload to file server v2 of image.png failed
    at uploadToFileServer ([REDACTED]\ts\session\utils\Attachments.js:74:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async MessageModel.uploadData ([REDACTED]\ts\models\message.js:525:47)
    at async ConversationModel.sendMessageJob ([REDACTED]\ts\models\conversation.js:1118:74)
    at async [REDACTED]\ts\models\conversation.js:513:13
```

**Comment by alecov** [comment]
Same in Linux.

Maybe related: image attachments are also not downloading at all. Both bugs have started quite recently (a few days ago).

**Comment by ThinkALot** [comment]
Same problem in Windows 11: I can't send images in Session version 1.11.4.

Details: This morning, I sent an image in version 1.10.8. Then I updated to 1.11.4, and was no longer able to send images. So I reverted back to 1.10.8, but now, even in the old version, I can't send images.

**Comment by KeeJef** [comment]
This should be resolved now, we have been experiencing some issues with automated disk fault checks on the file attachment server

**Comment by billygnosis2007** [comment]
This isn't resolved.  Still seeing this, from the "receiver" side, as @alecov mentioned above, as of today.

It seems to be instance related, as in, I can clear device data and sometimes get it to work next time by restoring my session.  Also doesn't seem to be attachment size related, either, as some attachments are quick to download and resolve, others stay in "loading" forever.

**Comment by ViktorWalter** [comment]
@KeeJef I'm experiencing this issue again - including the ENETUNREACH messages. Is the same thing happening?

**Comment by KeeJef** [comment]
> @KeeJef I'm experiencing this issue again - including the ENETUNREACH messages. Is the same thing happening?

Hey, do you have device logs from the device that was running into this issue?
